import { useState } from 'react';
import { Pagination } from 'antd';

function Table() {
    const invoicesmockData: any = [
        {
            invId: 1,
            logFisId: 123,
            vatnumber: 'VAT123456',
            sendDatetime: '2024-04-04T12:00:00Z',
            IIC: 'IIC123',
            FIC: 'FIC456',
            businUnitCode: 'BUS001',
            InvNum: 'INV001',
            InvOrdNum: 1,
            TypeOfInv: 'Type A',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-04T12:00:00Z',
            OperatorCode: 'OP123',
            SoftCode: 'SOFT001',
            TCRCode: 'TCR001',
            TotPrice: 100.0,
            TotPriceWoVAT: 80.0,
            TotVATAmt: 20.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Card',
            PayMethodAmt: '100.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 2,
            logFisId: 456,
            vatnumber: 'VAT654321',
            sendDatetime: '2024-04-05T12:00:00Z',
            IIC: 'IIC456',
            FIC: 'FIC789',
            businUnitCode: 'BUS002',
            InvNum: 'INV002',
            InvOrdNum: 2,
            TypeOfInv: 'Type B',
            IsIssuerInVAT: false,
            IsEinvoice: true,
            IsReverseCharge: true,
            IsSimplifiedInv: false,
            IssueDateTimeUTC: '2024-04-05T12:00:00Z',
            OperatorCode: 'OP456',
            SoftCode: 'SOFT002',
            TCRCode: 'TCR002',
            TotPrice: 200.0,
            TotPriceWoVAT: 160.0,
            TotVATAmt: 40.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Cash',
            PayMethodAmt: '200.00',
            CorrInvIICRef: 'IICREF123',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 3,
            logFisId: 789,
            vatnumber: 'VAT987654',
            sendDatetime: '2024-04-06T12:00:00Z',
            IIC: 'IIC789',
            FIC: 'FIC012',
            businUnitCode: 'BUS003',
            InvNum: 'INV003',
            InvOrdNum: 3,
            TypeOfInv: 'Type C',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-06T12:00:00Z',
            OperatorCode: 'OP789',
            SoftCode: 'SOFT003',
            TCRCode: 'TCR003',
            TotPrice: 300.0,
            TotPriceWoVAT: 240.0,
            TotVATAmt: 60.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Credit',
            PayMethodAmt: '300.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 1,
            logFisId: 123,
            vatnumber: 'VAT123456',
            sendDatetime: '2024-04-04T12:00:00Z',
            IIC: 'IIC123',
            FIC: 'FIC456',
            businUnitCode: 'BUS001',
            InvNum: 'INV001',
            InvOrdNum: 1,
            TypeOfInv: 'Type A',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-04T12:00:00Z',
            OperatorCode: 'OP123',
            SoftCode: 'SOFT001',
            TCRCode: 'TCR001',
            TotPrice: 100.0,
            TotPriceWoVAT: 80.0,
            TotVATAmt: 20.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Card',
            PayMethodAmt: '100.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 2,
            logFisId: 456,
            vatnumber: 'VAT654321',
            sendDatetime: '2024-04-05T12:00:00Z',
            IIC: 'IIC456',
            FIC: 'FIC789',
            businUnitCode: 'BUS002',
            InvNum: 'INV002',
            InvOrdNum: 2,
            TypeOfInv: 'Type B',
            IsIssuerInVAT: false,
            IsEinvoice: true,
            IsReverseCharge: true,
            IsSimplifiedInv: false,
            IssueDateTimeUTC: '2024-04-05T12:00:00Z',
            OperatorCode: 'OP456',
            SoftCode: 'SOFT002',
            TCRCode: 'TCR002',
            TotPrice: 200.0,
            TotPriceWoVAT: 160.0,
            TotVATAmt: 40.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Cash',
            PayMethodAmt: '200.00',
            CorrInvIICRef: 'IICREF123',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 3,
            logFisId: 789,
            vatnumber: 'VAT987654',
            sendDatetime: '2024-04-06T12:00:00Z',
            IIC: 'IIC789',
            FIC: 'FIC012',
            businUnitCode: 'BUS003',
            InvNum: 'INV003',
            InvOrdNum: 3,
            TypeOfInv: 'Type C',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-06T12:00:00Z',
            OperatorCode: 'OP789',
            SoftCode: 'SOFT003',
            TCRCode: 'TCR003',
            TotPrice: 300.0,
            TotPriceWoVAT: 240.0,
            TotVATAmt: 60.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Credit',
            PayMethodAmt: '300.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 1,
            logFisId: 123,
            vatnumber: 'VAT123456',
            sendDatetime: '2024-04-04T12:00:00Z',
            IIC: 'IIC123',
            FIC: 'FIC456',
            businUnitCode: 'BUS001',
            InvNum: 'INV001',
            InvOrdNum: 1,
            TypeOfInv: 'Type A',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-04T12:00:00Z',
            OperatorCode: 'OP123',
            SoftCode: 'SOFT001',
            TCRCode: 'TCR001',
            TotPrice: 100.0,
            TotPriceWoVAT: 80.0,
            TotVATAmt: 20.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Card',
            PayMethodAmt: '100.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 2,
            logFisId: 456,
            vatnumber: 'VAT654321',
            sendDatetime: '2024-04-05T12:00:00Z',
            IIC: 'IIC456',
            FIC: 'FIC789',
            businUnitCode: 'BUS002',
            InvNum: 'INV002',
            InvOrdNum: 2,
            TypeOfInv: 'Type B',
            IsIssuerInVAT: false,
            IsEinvoice: true,
            IsReverseCharge: true,
            IsSimplifiedInv: false,
            IssueDateTimeUTC: '2024-04-05T12:00:00Z',
            OperatorCode: 'OP456',
            SoftCode: 'SOFT002',
            TCRCode: 'TCR002',
            TotPrice: 200.0,
            TotPriceWoVAT: 160.0,
            TotVATAmt: 40.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Cash',
            PayMethodAmt: '200.00',
            CorrInvIICRef: 'IICREF123',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 3,
            logFisId: 789,
            vatnumber: 'VAT987654',
            sendDatetime: '2024-04-06T12:00:00Z',
            IIC: 'IIC789',
            FIC: 'FIC012',
            businUnitCode: 'BUS003',
            InvNum: 'INV003',
            InvOrdNum: 3,
            TypeOfInv: 'Type C',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-06T12:00:00Z',
            OperatorCode: 'OP789',
            SoftCode: 'SOFT003',
            TCRCode: 'TCR003',
            TotPrice: 300.0,
            TotPriceWoVAT: 240.0,
            TotVATAmt: 60.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Credit',
            PayMethodAmt: '300.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 1,
            logFisId: 123,
            vatnumber: 'VAT123456',
            sendDatetime: '2024-04-04T12:00:00Z',
            IIC: 'IIC123',
            FIC: 'FIC456',
            businUnitCode: 'BUS001',
            InvNum: 'INV001',
            InvOrdNum: 1,
            TypeOfInv: 'Type A',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-04T12:00:00Z',
            OperatorCode: 'OP123',
            SoftCode: 'SOFT001',
            TCRCode: 'TCR001',
            TotPrice: 100.0,
            TotPriceWoVAT: 80.0,
            TotVATAmt: 20.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Card',
            PayMethodAmt: '100.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 2,
            logFisId: 456,
            vatnumber: 'VAT654321',
            sendDatetime: '2024-04-05T12:00:00Z',
            IIC: 'IIC456',
            FIC: 'FIC789',
            businUnitCode: 'BUS002',
            InvNum: 'INV002',
            InvOrdNum: 2,
            TypeOfInv: 'Type B',
            IsIssuerInVAT: false,
            IsEinvoice: true,
            IsReverseCharge: true,
            IsSimplifiedInv: false,
            IssueDateTimeUTC: '2024-04-05T12:00:00Z',
            OperatorCode: 'OP456',
            SoftCode: 'SOFT002',
            TCRCode: 'TCR002',
            TotPrice: 200.0,
            TotPriceWoVAT: 160.0,
            TotVATAmt: 40.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Cash',
            PayMethodAmt: '200.00',
            CorrInvIICRef: 'IICREF123',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 3,
            logFisId: 789,
            vatnumber: 'VAT987654',
            sendDatetime: '2024-04-06T12:00:00Z',
            IIC: 'IIC789',
            FIC: 'FIC012',
            businUnitCode: 'BUS003',
            InvNum: 'INV003',
            InvOrdNum: 3,
            TypeOfInv: 'Type C',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-06T12:00:00Z',
            OperatorCode: 'OP789',
            SoftCode: 'SOFT003',
            TCRCode: 'TCR003',
            TotPrice: 300.0,
            TotPriceWoVAT: 240.0,
            TotVATAmt: 60.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Credit',
            PayMethodAmt: '300.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 1,
            logFisId: 123,
            vatnumber: 'VAT123456',
            sendDatetime: '2024-04-04T12:00:00Z',
            IIC: 'IIC123',
            FIC: 'FIC456',
            businUnitCode: 'BUS001',
            InvNum: 'INV001',
            InvOrdNum: 1,
            TypeOfInv: 'Type A',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-04T12:00:00Z',
            OperatorCode: 'OP123',
            SoftCode: 'SOFT001',
            TCRCode: 'TCR001',
            TotPrice: 100.0,
            TotPriceWoVAT: 80.0,
            TotVATAmt: 20.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Card',
            PayMethodAmt: '100.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 2,
            logFisId: 456,
            vatnumber: 'VAT654321',
            sendDatetime: '2024-04-05T12:00:00Z',
            IIC: 'IIC456',
            FIC: 'FIC789',
            businUnitCode: 'BUS002',
            InvNum: 'INV002',
            InvOrdNum: 2,
            TypeOfInv: 'Type B',
            IsIssuerInVAT: false,
            IsEinvoice: true,
            IsReverseCharge: true,
            IsSimplifiedInv: false,
            IssueDateTimeUTC: '2024-04-05T12:00:00Z',
            OperatorCode: 'OP456',
            SoftCode: 'SOFT002',
            TCRCode: 'TCR002',
            TotPrice: 200.0,
            TotPriceWoVAT: 160.0,
            TotVATAmt: 40.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Cash',
            PayMethodAmt: '200.00',
            CorrInvIICRef: 'IICREF123',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
        {
            invId: 3,
            logFisId: 789,
            vatnumber: 'VAT987654',
            sendDatetime: '2024-04-06T12:00:00Z',
            IIC: 'IIC789',
            FIC: 'FIC012',
            businUnitCode: 'BUS003',
            InvNum: 'INV003',
            InvOrdNum: 3,
            TypeOfInv: 'Type C',
            IsIssuerInVAT: true,
            IsEinvoice: false,
            IsReverseCharge: false,
            IsSimplifiedInv: true,
            IssueDateTimeUTC: '2024-04-06T12:00:00Z',
            OperatorCode: 'OP789',
            SoftCode: 'SOFT003',
            TCRCode: 'TCR003',
            TotPrice: 300.0,
            TotPriceWoVAT: 240.0,
            TotVATAmt: 60.0,
            TaxFreeAmt: 0,
            PayMethodType: 'Credit',
            PayMethodAmt: '300.00',
            CorrInvIICRef: '',
            CorrIssueDateTimeUTC: '',
            CorrType: '',
            CurrencyCode: 'USD',
            CurrencyExRate: 1.0,
            CurrencyIsBuying: false,
            SellerName: 'Seller Inc.',
            SellerIDType: 'ID',
            SellerIDNum: 'SELLERID123',
            SellerCountry: 'Country A',
            SellerTown: 'Town A',
            SellerAddress: 'Address A',
            BuyerName: 'Buyer Corp.',
            BuyerIDType: 'ID',
            BuyerIDNum: 'BUYERID456',
            BuyerCountry: 'Country B',
            BuyerTown: 'Town B',
            BuyerAddress: 'Address B',
            ErrorCode: false,
            ErrorMessage: '',
            TypeOfSelfIss: 'Type B',
        },
    ];
    const columnNames = [
        'Quantity',
        'Vat',
        'OperatorCode',
        'invDate',
        'BusinUnitCode',
        'BuyerName',
        'InvOrdNum',
        'BuyerIDNum',
        'BuyerTown',
        'NUIS',
        'TCRCode',
        'NSLF',
        'Amount',
        'InvNum',
        'NIVF',
        'Unit',
        'ProductName',
        'IsEinvoice',
        'SellerName',
        'TypeOfInv',
        'SoftCode',
        'SellerAddress',
        'Price',
        'PayMethodType',
        'BuyerIDType',
    ];

    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage] = useState(7);

    const [selectedArray] = useState<number[]>([]);

    const [loading ] = useState(false);
    const [data] = useState(invoicesmockData);

    // Slice data to display on the current page
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = Math.min(startIndex + itemsPerPage, data?.length || 0);
    const currentData = data?.slice(startIndex, endIndex) || [];

    const handlePageChange = (page: any) => {
        setCurrentPage(page);
    };

    return (
        <>
            <div className="relative overflow-x-auto shadow-md sm:rounded-lg">
                <table className="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                    <thead className="h-[40px] text-xs text-gray-700 uppercase bg-gray-500 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" className="p-4">
                                <div className="flex items-center">
                                    {/* <input
                                        onClick={() => {
                                            handleAllPageSelected();
                                        }}
                                        id="checkbox-all-search"
                                        type="checkbox"
                                        className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                                    /> */}
                                    <label htmlFor="checkbox-all-search" className="sr-only">
                                        checkbox
                                    </label>
                                </div>
                            </th>
                            {columnNames.map((columnName, index) => (
                                <th key={index} scope="col" className="px-6 ">
                                    {columnName}
                                </th>
                            ))}
                            <th scope="col" className="px-6 ">
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody className=" w-full">
                        {loading === false ? (
                            currentData.map((data, index) => (
                                <tr
                                    key={index + startIndex}
                                    className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                                    <td className="w-4 p-4">
                                        <div className="flex items-center whitespace-nowrap">
                                            <input
                                                defaultChecked={selectedArray.includes(
                                                    index + startIndex,
                                                )}
                                                onChange={() => {
                                                    // handleSelected(index + startIndex, data);
                                                }}
                                                id={`checkbox-table-search-${index}`}
                                                type="checkbox"
                                                className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                                            />

                                            <label
                                                htmlFor={`checkbox-table-search-${index}`}
                                                className="sr-only">
                                                checkbox
                                            </label>
                                        </div>
                                    </td>

                                    {columnNames.map((columnName, colIndex) => (
                                        <td
                                            key={colIndex}
                                            className="px-6 whitespace-nowrap ml-[33%]">
                                            {data[columnName]}
                                        </td>
                                    ))}

                                    <td className="px-6 py-4">
                                        <a
                                            href="#"
                                            className="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            ))
                        ) : (
                            // Render spinner if data array is empty
                            <tr>
                                <td
                                    colSpan={columnNames.length + 2}
                                    className="px-6 py-4 flex justify-center w-full">
                                    <div className=" "></div>
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
            <div className="mt-2 flex justify-end">
                <Pagination
                    defaultCurrent={1}
                    total={data?.length || 0}
                    pageSize={itemsPerPage}
                    onChange={handlePageChange}
                    hideOnSinglePage
                />
            </div>
        </>
    );
}

export default Table;