FROM node:20-alpine as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run  build

#Stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
